services:
  - type: web
    name: career-prediction-api
    env: python
    buildCommand: pip install -r requirements.txt && python scripts/ensure_model.py
    startCommand: gunicorn scripts.flask_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free 